### ISSUE TITLE
importContacts doesn't set None-type variables correctly

### ISSUE THREAD

**Issue by znicholasbrown** [Telerivet/telerivet-python-client#6]
Hi! I believe I found a bug when calling the `importContacts` route. When a contact variable (`contact.vars.x`) is set to `None`, the variable is never removed from the contact as described in the docs and in the same way `contact.save()` works.
I think the issue is here:
https://github.com/Telerivet/telerivet-python-client/blob/05effecd385c9327972b40c26d1a4f273c5b9590/telerivet/__init__.py#L159-L161

which doesn't allow `dirty_props` as the `Entity` class `save` method does.

**Comment by youngj** [comment]
Thanks for letting us know. This turned out to be a bug on Telerivet's server, not in the client library. It should be fixed now without needing to change the client library.  For POST requests, the body is encoded using `json.dumps` which encodes `None` as `null` as expected.  `encodeParamsRec` is only called for parameters in the query string of GET requests.

**Comment by znicholasbrown** [comment]
Much appreciated @youngj!
